version: '3.9'

services:

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.0
    container_name: cockroach
    ports:
      - "26257:26257"
      # - "8000:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    networks:
      - ticket-network
    healthcheck:
      test: ["CMD", "cockroach", "sql", "--insecure", "--execute=SELECT 1"]
      interval: 5s
      timeout: 2s
      retries: 5


  migrate:
    image: migrate/migrate:latest
    container_name: migration
    depends_on:
      cockroachdb:
        condition: service_healthy 
    
    volumes:
      - ./internal/data/migrations:/migrations
    entrypoint: ["migrate", "-path", "/migrations", "-database", "cockroachdb://root@cockroachdb:26257/tickets?sslmode=disable","up"]


    networks:
      - ticket-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: myapp
    # env_file: .env
    environment:
      - DB_HOST=cockroachdb
      - DB_PORT=26257
      - DB_USER=root
      - DB_NAME=tickets
    ports:
      - 8080:8080
    depends_on:
      - cockroachdb
      - migrate 
    networks:
      - ticket-network
     
volumes:
  cockroach-data:

networks:
  ticket-network: