version: '3.9'

services:

  db:
    image: postgres:13
    restart: always
    environment:
     - POSTGRES_USER=*****
     - POSTGRES_PASSWORD=*******
     - POSTGRES_DB=tickets
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ticket-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
     - DB_HOST=db
     - DB_PORT=5432
     - DB_USER=******
     - DB_PASSWORD=*******
     - DB_NAME=tickets
     - GIN_MODE=release
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - ticket-network

  nginx:
   image: nginx:latest
   restart: always
   ports:
     - 80:80
     - 443:443
   volumes:
     - ./var/www/html:/usr/share/nginx/html
     - ./nginx/conf/:/etc/nginx/conf.d/:ro
   depends_on:
     - app
   networks:
     - ticket-network

volumes:
  postgres-data:

networks:
  ticket-network: