
dbconn: postgres://root@localhost:26257/tickets?sslmode=disable
server: 
  host: 
  port: 8080
  read_time_out: 10s
sms: 
  token: 
  url: 
  template: you have bought event ticket. your ticket id is %v.
email: 
  host: localhost
  user_name: 
  password: 
  subject: s
payment:
  url: 
token: 
  key: "01234567890123456789012345678901"
  duration: 2m