
dbconn: 
server: 
  port: 8080
  read_time_out: 5
payment:
  publishable_key: 
  secret_key: 
sms: 
  token: 
  url: 
  template: you have bought event ticket. your ticket id is %v.
email: 
  host: localhost
  user_name: 
  password: 
  subject:s
