
dbconn: postgres://sibhat:sibhat@localhost:5432/tickets?sslmode=disable
server: 
  port: 8080
  read_time_out: 5
sms: 
  token: 
  url: 
  template: you have bought event ticket. your ticket id is %v.
email: 
  host: localhost
  user_name: 
  password: 
  subject: s
payment:
token: 
  key: "01234567890123456789012345678901"
  duration: 60s