version: "2"

sql:
  - schema: "../internal/data/migrations"
    queries: "../internal/data/queries"
    engine: "postgresql"

    gen:
      go:
        package: "db"
        out: "../internal/data/db"
        sql_package: "pgx/v4"