// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"time"
)

type User struct {
	ID            int32
	FirstName     string
	LastName      string
	Phone         string
	Email         string
	Nonce         string
	PaymentStatus string
	SessionID     string
	CheckIn       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
