// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
	"time"
)

type Payment struct {
	ID            int32
	UserID        int32
	PaymentStatus string
	IntentID      string
	CheckInStatus string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID        int32
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
