// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLine(ctx context.Context, arg CreateLineParams) (Line, error)
	CreateTrip(ctx context.Context, arg CreateTripParams) (LineTrip, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetLine(ctx context.Context, id uuid.UUID) (Line, error)
	GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error)
	GetTokenData(ctx context.Context) (GetTokenDataRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	StoreCheckoutSession(ctx context.Context, arg StoreCheckoutSessionParams) (Session, error)
	UpdateLine(ctx context.Context, arg UpdateLineParams) (Line, error)
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
