// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tickets.sql

package db

import (
	"context"
)

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets SET status ='Onhold' WHERE ticket_no=$1 AND bus_no=$2 AND trip_id=$3 RETURNING trip_id, bus_no, ticket_no, status
`

type UpdateTicketStatusParams struct {
	TicketNo int32
	BusNo    int32
	TripID   int32
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.TicketNo, arg.BusNo, arg.TripID)
	var i Ticket
	err := row.Scan(
		&i.TripID,
		&i.BusNo,
		&i.TicketNo,
		&i.Status,
	)
	return i, err
}
