// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tickets.sql

package db

import (
	"context"
)

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets SET status =$1 WHERE id=$2 RETURNING id,trip_id, bus_no, ticket_no, status
`

type UpdateTicketStatusParams struct {
	ID string
	Status string
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.Status,arg.ID)
	var i Ticket
	err := row.Scan(
		&i.TripID,
		&i.BusNo,
		&i.TicketNo,
		&i.Status,
	)
	return i, err
}
