// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: token.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTokenData = `-- name: GetTokenData :one
select u.id,
    t.id
from users u
    INNER JOIN tickets t on t.user_id = u.id
`

type GetTokenDataRow struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

func (q *Queries) GetTokenData(ctx context.Context) (GetTokenDataRow, error) {
	row := q.db.QueryRow(ctx, getTokenData)
	var i GetTokenDataRow
	err := row.Scan(&i.ID, &i.ID_2)
	return i, err
}
